#ifndef ITEMS_H
#define ITEMS_H

#include "common.h"

// Should match the structure and values generated by assets/data/json2tfs.py

typedef enum ItemEffect {
    IE_HEAL,  // Heals a phone by X% (X being the item's effect parameter)
    IE_REVIVE,  // Revives a phone with X% health
    IE_UPGRADE,  // Upgrades a phone's specs (screen, battery, cover, or board) X times
    IE_REPAIR,  // Upgrades a phone's status (screen status, batt status, etc) X times
    IE_COMBINE  // Combines two phones into one with better specs (X is unused)
} ItemEffect;

// General information about an item, not specific to an item the user has in their bag
typedef struct ItemSpecs {
    char name[32];
    char description[128];
    ItemEffect effect;
    int effectParameter;
    char sprite[32];
    int pocket;  // which bag pocket this item belongs in
} ItemSpecs;

// Item that the user has in their bag (ID refers to index in the items.tfs file)
typedef struct Item {
    int id;
    int count;
} Item;

typedef struct ItemDatabase {
    u32 size;
    ItemSpecs items[];
} ItemDatabase;

#endif