#ifndef SKILLS_H
#define SKILLS_H

#include "common.h"

// Should match the structure and values generated by assets/data/json2tfs.py

typedef enum SkillType {
    SKT_SCREEN,
    SKT_BOARD,
    SKT_COVER,
    SKT_BATTERY
} SkillType;

static const char *skillTypes[4] = {
    "Screen", "Board", "Cover", "Battery"
};

typedef enum SkillEffect {
    SE_NONE,  // Does nothing (e.g. the secondary effect if the skill only has one effect)
    SE_DAMAGE,  // Does X damage to the enemy (X being the effect parameter)
    SE_SELF_DAMAGE,  // Does X damage to player
    SE_HEAL,  // Gives X health to player
    SE_DRAIN,  // Drains X health from the enemy and gives it to the user
    SE_CONFUSE,  // Confuses the enemy with a X% chance
    SE_ATK_UP,  // Increases the user's attack for X turns
    SE_DEF_UP,  // Increases the user's defense for X turns
    SE_ACCURACY_UP,  // Increases the player's accuracy for X turns
    SE_ACCURACY_DOWN,  // Decreases enemy's accuracy for X turns

    // Effects exclusive to specific skills
    SE_STOMP,  // Deals damage based on body weight
    SE_FLEX_RIP,  // Deals increased damage to flip/slider phones
} SkillEffect;

typedef struct SkillSpecs {
    char name[16];
    char description[128];
    SkillType type;

    struct {
        SkillEffect effect;
        int parameter;
        int chance;
    } effects[2];

    char learnByPhones[256];
    char animation[64];
    int animationTarget; // 0 = self, 1 = enemy
} SkillSpecs;

typedef struct SkillDatabase {
    u32 size;
    SkillSpecs skills[];
} SkillDatabase;

#endif