name: Build project
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup build environment
        run: |
          sudo apt update
          sudo apt install mingw-w64
          make setup
          make setup PLATFORM=Windows_NT
          
      - name: Build project
        run: |
          make
          make PLATFORM=Windows_NT

      - uses: actions/upload-artifact@v3.0.0
        with:
          name: romphonix-linux
          path: |
            bin/romphonix
            rpxmap
            
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: romphonix-windows
          path: |
            bin/romphonix.exe
            rpxmap.exe